version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-c
    restart: unless-stopped
    ports:
      - 8000:80
      - 8001:81
      - 8002:82
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - industria

  app:
    image: quotesun/bedrock:7.4
    container_name: bedrock-c
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - industria
  
  db:
    image: mysql:8.0
    container_name: mysql-c
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - industria

volumes:
  db-volume:

networks:
  industria:
    driver: bridge

